# Generated by Django 4.2.14 on 2025-04-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_apimodel_passkey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_manage_master_users', 'Can manage master users')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_master',
            field=models.BooleanField(default=False, help_text='Designates whether this user has master privileges.', verbose_name='master user'),
        ),
    ]
