# Generated by Django 4.2.14 on 2025-04-21 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_user_options_user_is_master'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_master',
        ),
    ]
