# Generated by Django 4.2.14 on 2025-04-21 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_user_options_user_is_master 4'),
        ('home', '0044_alter_user_options_remove_user_is_master'),
    ]

    operations = [
    ]
