# Generated by Django 4.2.14 on 2025-04-30 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_cyberchallenge_fts'),
        ('home', '0046_alter_article_content'),
    ]

    operations = [
    ]
