# Generated by Django 4.2.14 on 2025-04-30 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_merge_20250501_0239'),
    ]

    operations = [
    ]
