# Generated by Django 4.2.14 on 2025-04-30 21:17

from django.db import migrations, models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_merge_20250501_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='webpage',
            table=None,
        ),
    ]
