# Generated by Django 4.2.14 on 2025-04-21 07:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0002_delete_pagecontent_alter_chatsession_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('page_path', models.CharField(help_text='Path to the page (e.g., /appattack/main)', max_length=255)),
                ('section', models.CharField(help_text='Section of the page (e.g., header, introduction, etc.)', max_length=100)),
                ('content', models.TextField()),
                ('keywords', models.TextField(help_text='Comma-separated keywords for search matching')),
                ('page_category', models.CharField(help_text='Category of page (e.g., appattack, challenges, etc.)', max_length=100)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority content will be shown first (0-10)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
