# Generated by Django 4.2.14 on 2025-04-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0004_chatsession_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_user_message',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
