# Generated by Django 4.2.14 on 2025-05-01 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot_app', '0005_remove_chatmessage_is_user_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomChatbotResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(help_text='Comma-separated keywords that will trigger this response')),
                ('response', models.TextField(help_text='The response that the chatbot should give when keywords are matched')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority responses will be checked first (0-10)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this custom response is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Associate this response with a specific project (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot_app.project')),
            ],
            options={
                'verbose_name': 'Custom Chatbot Response',
                'verbose_name_plural': 'Custom Chatbot Responses',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
