# Generated by Django 4.2.14 on 2025-05-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0008_unsearchablemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchablePost',
        ),
        migrations.DeleteModel(
            name='UnsearchableModel',
        ),
    ]
