# Generated by Django 4.2.14 on 2025-05-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0009_delete_searchablepost_delete_unsearchablemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_bot',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional data about the message, like sentiment analysis', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(default='user', help_text="Either 'user' or 'bot'", max_length=50),
        ),
    ]
