# Generated by Django 4.2.14 on 2025-05-02 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0010_remove_chatmessage_is_bot_chatmessage_metadata_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'ordering': ['-priority', '-updated_at']},
        ),
        migrations.RenameField(
            model_name='pagecontent',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='pagecontent',
            name='page_category',
        ),
        migrations.RemoveField(
            model_name='pagecontent',
            name='page_path',
        ),
        migrations.RemoveField(
            model_name='pagecontent',
            name='section',
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher priority items appear first in search results'),
        ),
    ]
